# Generated by Django 5.1 on 2024-08-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания категории')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего обновления категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('priority', models.IntegerField(default=1, verbose_name='Приоритет задачи')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Статус задачи')),
                ('dua_date', models.DateTimeField(null=True, verbose_name='Дата и время выполнения задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания задачи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего обновления задачи')),
                ('categories', models.ManyToManyField(to='core.category')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
