# Generated by Django 5.1 on 2024-08-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dua_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время выполнения задачи'),
        ),
    ]
